# SPDX-License-Identifier: MIT
# Copyright David Kristiansen

add_newline = true
[line_break]
disabled = false

command_timeout = 1000

# [character]
# success_symbol = "[âœ](bold green) "
# error_symbol = "[âœ—](bold red) "

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
truncate_to_repo = false

[cmd_duration]
min_time = 0
format = "took [$duration](bold yellow)"

[status]
# style = "bg:blue"
# symbol = "ğŸ”´ "
# success_symbol = "ğŸŸ¢ SUCCESS"
format = '[$status]($style) '
map_symbol = true
disabled = false
