# SPDX-License-Identifier: MIT
# Copyright David Kristiansen

[settings]
pipx_uvx = true
experimental = true
jobs = 32
idiomatic_version_file_enable_tools = ["python"]

[tool_alias]
thefuck = "pipx:thefuck"

[tools]
neovim = "nightly"
bat = "latest"
fd = "latest"
ripgrep = "latest"
fzf = "latest"
cmake = "latest"
github-cli = "latest"
sqlite = "latest"
stylua = "latest"
bat-extras = "latest"
zig = "latest"
pre-commit = "latest"

# node
nodejs = "latest"
"npm:prettier" = "latest"

# Python
python = "3.14"
pipx = "latest"
uv = "0.9.2"

thefuck = { version = "latest", uvx_args = "--python 3.11" }

# Go
go = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"

# Rust
rust = "latest"
cargo-binstall = "latest"
"cargo:eza" = "latest"
"cargo:zoxide" = "latest"
"cargo:yazi-build" = "latest"
"cargo:binsider" = "latest"
"npm:markdown-toc" = "latest"
"pipx:isort" = "latest"

# Aqua
"aqua:ruff" = "latest"
"npm:tree-sitter-cli" = "latest"
direnv = "latest"
# gemini-cli = "latest"
delta = "latest"
gh = "latest"
"npm:copilot" = "latest"
"npm:mcp-hub" = "latest"
"pipx:jiratui" = "latest"
java = "26"
gemini-cli = "latest"
gemini = "latest"
"pipx:platformio" = "latest"
lazygit = "latest"
"go:github.com/r00tman/corrupter" = "latest"
"npm:@devcontainers/cli" = "latest"
"cargo:fixit-cli" = "latest"
